#pragma once

#define NEWOPCODES_VERSION_MAIN  2
#define NEWOPCODES_VERSION_MAJOR 5
#define NEWOPCODES_VERSION_MINOR 1

#define NEWOPCODES_TO_STR_IMPL(x) #x
#define NEWOPCODES_TO_STR(x) NEWOPCODES_TO_STR_IMPL(x)
#define NEWOPCODES_VERSION_STR \
	NEWOPCODES_TO_STR(NEWOPCODES_VERSION_MAIN.NEWOPCODES_VERSION_MAJOR.NEWOPCODES_VERSION_MINOR)
